# Import Required Libraries

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Load Dataset File

In [10]:
db=pd.read_csv("netflix_titles.csv")

### Display the first five rows

In [14]:
db.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

# Understanding The Data

### 1- what is the coulmns Names ?

In [22]:
db.columns

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description'],
      dtype='object')

### 2- What are the count and data type of every column ?

In [26]:
db.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   object
 1   type          8807 non-null   object
 2   title         8807 non-null   object
 3   director      6173 non-null   object
 4   cast          7982 non-null   object
 5   country       7976 non-null   object
 6   date_added    8797 non-null   object
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   object
 9   duration      8804 non-null   object
 10  listed_in     8807 non-null   object
 11  description   8807 non-null   object
dtypes: int64(1), object(11)
memory usage: 825.8+ KB

### 3- what is the descriptive statistics for numerical columns ?

In [28]:
db.describe()

       release_year
count   8807.000000
mean    2014.180198
std        8.819312
min     1925.000000
25%     2013.000000
50%     2017.000000
75%     2019.000000
max     2021.000000

### 4- what is the analysis of categorical columns ?

In [29]:
db.describe(include="object")

,show_id,type,title,director,cast,country,date_added,rating,duration,listed_in,description
count,8807,8807,8807,6173,7982,7976,8797,8803,8804,8807,8807
unique,8807,2,8807,4528,7692,748,1767,17,220,514,8775
top,s1,Movie,Dick Johnson Is Dead,Rajiv Chilaka,David Attenborough,United States,"January 1, 2020",TV-MA,1 Season,"Dramas, International Movies","Paranormal activity at a lush, abandoned prope..."
freq,1,6131,1,19,19,2818,109,3207,1793,362,4

# Data Cleaning & Preparation

### Checking the number of missing values in each column

In [34]:
db.isna().sum()

show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

### Checking the precentage of missing data in each coulmn and order it ascendingly

In [42]:
missing_percentage = (db.isnull().sum() / len(db)) * 100
missing_percentage.sort_values(ascending = False)

director        29.908028
country          9.435676
cast             9.367549
date_added       0.113546
rating           0.045418
duration         0.034064
show_id          0.000000
type             0.000000
title            0.000000
release_year     0.000000
listed_in        0.000000
description      0.000000
dtype: float64

### Missing Value Analysis

The dataset contains missing values in six columns:

* Director, Cast, and Country is strings and contain a significant number of missing values. Removing these rows would result in the loss of a large amount of valuable data, so these missing values will be replaced with "Unknown".

* rating i will Replace missing ratings with "Unavailable"

* Date Added is mixed-type values so, instead of removing missing values. i will seperate it to 2 other coilmns but aslo filtered out the rows with Nan values into 0. 

* some 'rating' values accidentally contain duration values (e.g., "74 min"). so, We move misplaced duration values from 'rating' to 'duration'

### Replacing (director, Cast, and Country) missing values with "Unknown"

In [70]:
db["director"]= db["director"].fillna("unknown")
db["cast"]=db["cast"].fillna("unknown")
db["country"]= db["country"].fillna("unknown")

In [72]:
# checking if missing values filled succsesfuly
db.isna().sum()

show_id          0
type             0
title            0
director         0
cast             0
country          0
date_added      10
release_year     0
rating           4
duration         3
listed_in        0
description      0
dtype: int64

### Replacing missing ratings with "Unavailable"

In [100]:
db['rating'] = db['rating'].fillna("Unavailable")

In [101]:
# checking if missing values filled succsesfuly
db.isna().sum()

show_id         0
type            0
title           0
director        0
cast            0
country         0
date_added      0
release_year    0
rating          0
duration        3
listed_in       0
description     0
month_added     0
year_added      0
dtype: int64

### now for Date_added i will seperate it into 2 coulmns (month added , year added) and replace missings with 0

In [102]:
# Extract the month word and 4-digit year directly using regular expressions
db["month_added"] = db["date_added"].str.extract(r"([A-Za-z]+)")
db["year_added"] = db["date_added"].str.extract(r"(\d{4})")

In [103]:
db["year_added"]=db["year_added"].fillna(0)
db["month_added"]=db["month_added"].fillna(0)
db["date_added"]=db["date_added"].fillna(0)

# checking if missing values filled succsesfuly
db.isna().sum()

show_id         0
type            0
title           0
director        0
cast            0
country         0
date_added      0
release_year    0
rating          0
duration        3
listed_in       0
description     0
month_added     0
year_added      0
dtype: int64

### Fix Mixed-Type & Column Inconsistencies ('duration' & 'rating')

In [107]:
# In the Netflix dataset, some 'rating' values accidentally contain duration values (e.g., "74 min")
# We move misplaced duration values from 'rating' to 'duration'

misplaced_mask = db['rating'].str.contains('min|Seasons', na=False)

db.loc[misplaced_mask, 'duration'] = db.loc[misplaced_mask, 'rating']
db.loc[misplaced_mask, 'rating'] = "Unavailable"

# Extract numerical duration and unit type into separate columns
db['duration_num'] = db['duration'].str.extract(r'(\d+)').astype(float)
db['duration_type'] = db['duration'].str.extract(r'([a-zA-Z]+)')

# Normalize unit names ('min' -> 'Minutes', 'Season'/'Seasons' -> 'Seasons')
db['duration_type'] = db['duration_type'].replace({
    'min': 'Minutes',
    'Season': 'Seasons',
    'Seasons': 'Seasons'
})

In [110]:
# checking the new columns
db.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,month_added,year_added,duration_num,duration_type
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,unknown,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",September,2021,90.0,Minutes
1,s2,TV Show,Blood & Water,unknown,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",September,2021,2.0,Seasons
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",unknown,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...,September,2021,1.0,Seasons
3,s4,TV Show,Jailbirds New Orleans,unknown,unknown,unknown,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo...",September,2021,1.0,Seasons
4,s5,TV Show,Kota Factory,unknown,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...,September,2021,2.0,Seasons

### Parse Dates & Create New Time Columns

In [111]:
# Clean date string formatting
clean_dates = db['date_added'].str.strip()

# Parse into proper pandas datetime objects
# Handles variations with or without spaces after the comma (e.g., "September 24, 2022")
db['date_added_dt'] = pd.to_datetime(
    clean_dates, format='%B %d, %Y', errors='coerce'
).fillna(
    pd.to_datetime(clean_dates, format='%B %d,%Y', errors='coerce')
)

# Extract new required feature columns
db['year_added'] = db['date_added_dt'].dt.year.astype('Int64')
db['month_added'] = db['date_added_dt'].dt.month_name()
db['month_added_num'] = db['date_added_dt'].dt.month.astype('Int64')

In [112]:
# Drop temporary helper column
db = db.drop(columns=['date_added_dt'])

### display final cleaned data info

In [114]:
print("\n--- Final Cleaned Info ---")
db.info()

--- Final Cleaned Info ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   show_id          8807 non-null   object
 1   type             8807 non-null   object
 2   title            8807 non-null   object
 3   director         8807 non-null   object
 4   cast             8807 non-null   object
 5   country          8807 non-null   object
 6   date_added       8807 non-null   object
 7   release_year     8807 non-null   int64
 8   rating           8807 non-null   object
 9   duration         8807 non-null   object
 10  listed_in        8807 non-null   object
 11  description      8807 non-null   object
 12  month_added      8797 non-null   object
 13  year_added       8797 non-null   Int64
 14  duration_num     8807 non-null   float64
 15  duration_type    8807 non-null   object
 16  month_added_num  8797 non-null   Int64
dtypes: Int64(2), float64(1), int64(1), object(13)
memory usage: 1.2+ MB

# Exporting cleaned DataFrame to CSV

In [115]:
db.to_csv("netflix_titles_cleaned.csv", index=False)
print("\nSuccess! Cleaned dataset saved to 'netflix_titles_cleaned.csv'.")

Success! Cleaned dataset saved to 'netflix_titles_cleaned.csv'.